module.exports.createHttpClient = require('./dist/es5/create-http-client')
module.exports.createRequestConfig = require('./dist/es5/create-request-config')
module.exports.enforceObjPath = require('./dist/es5/enforce-obj-path')
module.exports.freezeSys = require('./dist/es5/freeze-sys')
module.exports.getUserAgentHeader = require('./dist/es5/get-user-agent')
module.exports.toPlainObject = require('./dist/es5/to-plain-object')
