version: 2.1

orbs:
  vault: contentful/vault@1
  node: circleci/node@5.2.0

jobs:
  test:
    docker:
      - image: cimg/node:18
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: npm run tsc
      - run: npm run lint
      - run: npm run prettier:check
      - run: npm run test:cover
  release:
    docker:
      - image: cimg/node:18
    steps:
      - checkout
      - vault/get-secrets: # Loads vault secrets
          template-preset: 'semantic-release-ecosystem'
      - node/install-packages
      - run: npm run build
      - run: npm run semantic-release
workflows:
  build_and_test:
    jobs:
      - test
      - release:
          context:
            - vault
          requires:
            - test
